services:
  db:
    image: mariadb:lts
    container_name: maria
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DATABASE}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
    ports:
      - "5306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./db/import:/db/import:ro
    command: ["--character-set-server=utf8mb4","--collation-server=utf8mb4_unicode_ci"]

  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    env_file: .env
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MARIADB_DATABASE}
      DB_USER: ${MARIADB_USER}
      DB_PASS: ${MARIADB_PASSWORD}
      PORT: 8081
    ports:
      - "8081:8081"
    depends_on:
      - db

  web:
    build:
      context: ./web
      args:
        VITE_API_BASE_URL: http://localhost:8081
    container_name: web
    restart: unless-stopped
    ports:
      - "3000:5173"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      - VITE_API_BASE_URL=http://localhost:8081
    command: ["npm","run","dev","--","--host"]
    depends_on:
      - api

volumes:
  db_data: